# Generated by Django 5.1.7 on 2025-03-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_exchange_accepted_exchange_declined'),
        ('users', '0005_notification_title_notification_user_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='books.exchange'),
        ),
    ]
