# Generated by Django 5.1.7 on 2025-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='desired_author',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='desired_isbn',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='desired_isbns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
