# Generated by Django 5.1.7 on 2025-03-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_wishlist_desired_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='books',
            new_name='book',
        ),
    ]
