# Generated by Django 5.1.7 on 2025-03-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_books_wishlist_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='book',
            new_name='books',
        ),
    ]
