# Generated by Django 5.1.7 on 2025-04-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_conversation_messages_alter_message_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
