# Generated by Django 5.1.7 on 2025-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_review_reviewed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='veto',
            field=models.BooleanField(default=False),
        ),
    ]
