# Generated by Django 5.1.7 on 2025-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userprofile_veto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recovery_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
