# Generated by Django 5.1.7 on 2025-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userprofile_recovery_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recovery_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
