# Generated by Django 5.1.7 on 2025-03-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_state_book_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='books.book'),
        ),
    ]
