# Generated by Django 5.1.7 on 2025-03-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_exchange_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='book',
        ),
        migrations.AddField(
            model_name='exchange',
            name='book_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to='books.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='book_from',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_given', to='books.book'),
            preserve_default=False,
        ),
    ]
