# Generated by Django 5.1.7 on 2025-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_exchange_book_exchange_book_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
