# Generated by Django 5.1.7 on 2025-04-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_review_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
    ]
